language: python
python:
  - "2.7"

before_install:
  - sudo apt-get install gfortran libopenblas-dev liblapack-dev

# command to install dependencies
# pip install scipy takes a lot of time and generates a lot of output. I want to get some output printed
# just to avoid the job from getting stopped.
# 
# Check https://github.com/statsmodels/statsmodels/issues/2184 for scipy=0.14
install:
  - pip install scipy=0.14 | awk 'NR % 250 == 0'
  - pip install .
  - pip install --allow-external=TA-Lib --allow-unverified=TA-Lib -r travis/requirements.txt

# command to run tests
# optimizer_testcase is ignored because it gets blocked in Travis.
# twitter_test is ignored because it requires credentials.
# talib_test is ignored until I get it to work on Travis.
script: nosetests --ignore-files=optimizer_testcase --ignore-files=twitter_test --ignore-files=talib_test
